config/routes.rb
RailsinstallerDemo::Application.routes.draw do
    resources :apps
  match '/help', to:'static_pages#help'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/new', to: 'apps#new'
  match 'apps/create', to: 'apps#show[:id]'
  match '/apps/[:id]', to:'apps#show[:id]'

  root :to => "static_pages#home"

end

app/models/app.rb
class App < ActiveRecord::Base
	attr_accessible :grs_ticket, :mobile_platform, :name, :name2, :business_unit,  :department_visibility,  :department_download,  :region_download,  
					:development_platform, :language, :developer_string, :special_reqs, :os_reqs, :testers,  :vendor_confirmation,  
					:description,  :version_notes,  :business_owner,  :support_contact, :source,  :release_date, :version_number

	validates :grs_ticket, presence: true
	validates :grs_ticket, :numericality => true
	validates :mobile_platform, presence: true
	validates :testers, presence: true  
	validates :vendor_confirmation, presence: true  
	validates :business_owner, presence: true 
	validates :support_contact, presence: true
	validates :source, presence: true 
	validates :name, presence: true 
	validates :name2, presence: true 
	validates :business_unit, presence: true  
	validates :department_visibility, presence: true  
	validates :department_download, presence: true 
	validates :region_download, presence: true  
	validates :development_platform, presence: true 
	validates :language, presence: true
	validates :developer_string, presence: true
	validates :release_date, presence: true
	validates :version_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def new
  	@app = App.new
  end

  def create
  	@app = App.new(params[:app])
  	if @app.save
  		redirect_to @app
  	else 
  		render 'new'
  	end
  end

  def show
  	@app = App.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/new.html.erb
<title>New App</title>
<h1>Submit an App!</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@app) do |f| %>
      <%= render 'shared/error_messages' %>

      GRS Ticket: <%= f.text_field :grs_ticket %>

      <!-- <%= f.label :grs_ticket %> -->
      <!-- <%= f.text_field :grs_ticket %> -->

    <div class="control-group">
    	<!-- <label class="control-label"><%= f.label :mobile_platform %></label> -->
      	<div class="controls">                 
        	Mobile Platform: <%= f.select :mobile_platform, options_for_select(['Android','Blackberry','iPad', 'iPhone', 'iTunes', 'Window']) %>
        </div>
		</div>

      Name (this is the App Store name): <%= f.text_field :name %>

      Name2 (this is the device icon name): <%= f.text_field :name2 %>

		<div class="control-group">
    	<label class="control-label"><%= f.label :business_unit %></label>
      	<div class="controls">                 
        	<%= f.select :business_unit, options_for_select(['All','CRDM','Cardiovascular', 'Neuro', 'Spinal', 'Surgical Technologies', 'Diabetes']) %>
        </div>
		</div>
 
         
     <div class="control-group">
    	<label class="control-label"><%= f.label :department_visibility %></label>
      	<div class="controls">                 
        	<%= f.select :department_visibility, options_for_select(['All','CRDM','Cardiovascular', 'Neuro', 'Spinal', 'Surgical Technologies', 'Diabetes']) %>
        </div>
		</div>

     <div class="control-group">
    	<label class="control-label"><%= f.label :department_download %></label>
      	<div class="controls">                 
        	<%= f.select :department_download, options_for_select(['All','CRDM','Cardiovascular', 'Neuro', 'Spinal', 'Surgical Technologies', 'Diabetes']) %>
        </div>
		</div>

	 <div class="control-group">
    	<label class="control-label"><%= f.label :region_download %></label>
      	<div class="controls">                 
        	<%= f.select :region_download, options_for_select(['All','CRDM','Cardiovascular', 'Neuro', 'Spinal', 'Surgical Technologies', 'Diabetes']) %>
        </div>
		</div>

      Release Date (YYYY-MM-DD): <%= f.text_field :release_date %>

      Version Number: <%= f.text_field :version_number %>

      
      <div class="controls">
      	<% @app.development_platform = "Xcode (4 or 4.2)" %>
      	<%= f.label :development_platform %>
      	<%= f.text_field :development_platform %> 

      	<!-- <input class="input-xlarge focused" id="focusedInput" type="text" value="Xcode (4 or 4.2)"> -->
      </div>
      	
     

      <%= f.label :language %>
      <%= f.text_field :language %>

      Special Requirements: <%= f.text_area :special_reqs %>

      OS Requirements: <%= f.text_field :os_reqs %>

      <%= f.label :testers %>
      <%= f.text_area :testers %>

      Vendor Confirmation: <%= f.text_area :vendor_confirmation %>

      Developer: <%= f.text_field :developer_string %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      Version Notes: <%= f.text_area :version_notes %>

      Business Owner: <%= f.text_field :business_owner %>

      Support Contact: <%= f.text_area :support_contact %>

      <%= f.label :source %>
      <%= f.text_area :source %>

      <br>

      <%= f.submit "Submit", class: "btn btn-large btn-primary", :confirm => "Are you sure this information is correct?" %>
    <% end %>
  </div>
</div>

app/views/apps/show.html.erb
<head>
<script>
	$('a[data-toggle="tab"]').on('shown', function (e) {
  	e.target // activated tab
  	e.relatedTarget // previous tab
	})
</script>
</head>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th><strong><em> Property </em></strong></th>
			<th><strong><em> Value </em></strong></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th> GRS Ticket </th>
			<th><%= @app.grs_ticket  %> </th>
		</tr>
		<tr>
			<th> Mobile Platform </th>
			<th><%= @app.mobile_platform  %> </th>
		</tr>
		<tr>
			<th> Name </th>
			<th><%= @app.name  %> </th>
		</tr>
		<tr>
			<th> Name2 </th>
			<th><%= @app.name2  %> </th>
		</tr>
		<tr>
			<th> Business Unit </th>
			<th><%= @app.business_unit  %> </th>
		</tr>
		<tr>
			<th> Department Visibility </th>
			<th><%= @app.department_visibility  %> </th>
		</tr>
		<tr>
			<th> Department Download </th>
			<th><%= @app.department_download %> </th>
		</tr>
		<tr>
			<th> Region Download </th>
			<th><%= @app.region_download %> </th>
		</tr>
		<tr>
			<th> Release date </th>
			<th><%= @app.release_date %> </th>
		</tr><tr>
			<th> Version Number </th>
			<th><%= @app.version_number %> </th>
		</tr>
		<tr>
			<th> Development Platform </th>
			<th><%= @app.development_platform %> </th>
		</tr>
		<tr>
			<th> Language </th>
			<th><%= @app.language %> </th>
		</tr>
		<tr>
			<th> Special Requirements </th>
			<th><%= @app.special_reqs %> </th>
		</tr>
		<tr>
			<th> OS Requirements </th>
			<th><%= @app.os_reqs %> </th>
		</tr>
		<tr>
			<th> Testers </th>
			<th><%= @app.testers %> </th>
		</tr>
		<tr>
			<th> Vendor Confirmation </th>
			<th><%= @app.vendor_confirmation %> </th>
		</tr>
		<tr>
			<th> Developer String </th>
			<th><%= @app.developer_string %> </th>
		</tr>
		<tr>
			<th> Description </th>
			<th><%= @app.description %> </th>
		</tr>
		<tr>
			<th> Version Notes </th>
			<th><%= @app.version_notes %> </th>
		</tr>
		<tr>
			<th> Business Owner </th>
			<th><%= @app.business_owner %> </th>
		</tr>
		<tr>
			<th> Support Contact </th>
			<th><%= @app.support_contact %> </th>
		</tr>
		<tr>
			<th> Source </th>
			<th><%= @app.source %> </th>
		</tr>
	</tbody>
</table>

<!-- <div class="tabbable tabs-left">
	<div class="alert alert-success">
		<p>Congratulations! <%= @app.name2 %> has been submitted!</p>
	</div>	
  <ul class="nav nav-tabs">
		<li class="active">
				<a href="#1A" data-toggle="tab">GRS Ticket #</a>
		</li>	
		<li>
				<a href="#1B" data-toggle="tab">Mobile Platform</a>
		</li>	
		<li>
				<a href="#1C" data-toggle="tab">Name</a>
		</li>	
		<li>
				<a href="#1D" data-toggle="tab">Name2</a>
		</li>	
		<li>
				<a href="#1E" data-toggle="tab">Business Unit</a>
		</li>	
		<li>
				<a href="#1F" data-toggle="tab">Department Visibility</a>
		</li>	
		<li>
				<a href="#1G" data-toggle="tab">Department Download</a>
		</li>	
		<li>
				<a href="#1H" data-toggle="tab">Region Download</a>
		</li>	
		<li>
				<a href="#1U" data-toggle="tab">Release Date</a>
		</li>	
		<li>
				<a href="#1V" data-toggle="tab">Version Number</a>
		</li>	
		<li>
				<a href="#1I" data-toggle="tab">Development Platform</a>
		</li>	
		<li>
				<a href="#1J" data-toggle="tab">Language</a>
		</li>	
		<li>
				<a href="#1L" data-toggle="tab">Spcial Requirements</a>
		</li>	
		<li>
				<a href="#1M" data-toggle="tab">OS Requirements</a>
		</li>	
		<li>
				<a href="#1N" data-toggle="tab">Testers</a>
		</li>	
		<li>
				<a href="#1O" data-toggle="tab">Vendor Confirmation</a>
		</li>	
		<li>
				<a href="#1K" data-toggle="tab">Developer String</a>
		</li>	
		<li>
				<a href="#1P" data-toggle="tab">Description</a>
		</li>	
		<li>
				<a href="#1Q" data-toggle="tab">Version Notes</a>
		</li>	
		<li>
				<a href="#1R" data-toggle="tab">Business Owner</a>
		</li>	
		<li>
				<a href="#1S" data-toggle="tab">Support Contact</a>
		</li>	
		<li>
				<a href="#1T" data-toggle="tab">Source</a>
		</li>	
  </ul>

  <div class="tab-content">
  	<div class="tab-pane active" id="1A">
  		<p><%=  @app.grs_ticket %></p>
  	</div>	
  	<div class="tab-pane" id="1B">
  		<p><%= @app.mobile_platform %></p>
  	</div>
  	<div class="tab-pane" id="1C">
  		<p><%= @app.name %></p>
  	</div>
  	<div class="tab-pane" id="1D">
  		<p><%= @app.name2 %></p>
  	</div>
  	<div class="tab-pane" id="1E">
  		<p><%= @app.business_unit %></p>
  	</div>
  	<div class="tab-pane" id="1F">
  		<p><%= @app.department_visibility %></p>
  	</div>
  	<div class="tab-pane" id="1G">
  		<p><%= @app.department_download %></p>
  	</div>
  	<div class="tab-pane" id="1H">
  		<p><%= @app.region_download %></p>
  	</div>
  	<div class="tab-pane" id="1U">
  		<p><%= @app.release_date %></p>
  	</div>
  	<div class="tab-pane" id="1V">
  		<p><%= @app.version_number %></p>
  	</div>
  	<div class="tab-pane" id="1I">
  		<p><%= @app.development_platform %></p>
  	</div>
  	<div class="tab-pane" id="1J">
  		<p><%= @app.language %></p>
  	</div>
  	<div class="tab-pane" id="1L">
  		<p><%= @app.special_reqs %></p>
  	</div>
  	<div class="tab-pane" id="1M">
  		<p><%= @app.os_reqs %></p>
  	</div>
  	<div class="tab-pane" id="1N">
  		<p><%= @app.testers %></p>
  	</div>
  	<div class="tab-pane" id="1O">
  		<p><%= @app.vendor_confirmation %></p>
  	</div>
  	<div class="tab-pane" id="1K">
  		<p><%= @app.developer_string %></p>
  	</div>
  	<div class="tab-pane" id="1P">
  		<p><%= @app.description %></p>
  	</div>
  	<div class="tab-pane" id="1Q">
  		<p><%= @app.version_notes %></p>
  	</div>
  	<div class="tab-pane" id="1R">
  		<p><%= @app.business_owner %></p>
  	</div>
  	<div class="tab-pane" id="1S">
  		<p><%= @app.support_contact %></p>
  	</div>
  	<div class="tab-pane" id="1T">
  		<p><%= @app.source %></p>
  	</div>
</div>-->

app/views/layouts/_footer.html.erb
<head>
  <style>
    footer {
        clear:both;
    }
  </style>
</head>
<footer class="footer">
  <small>
    <a href="/">App Submission</a>
    by Brandon Smith
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   help_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
          <a class="brand" href="/">App Submit</a>
          <li><%= link_to "Submit an app", new_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App Submission Web App</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
     <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    </body>
 </html>

app/views/shared/_error_messages.html.erb
<% if @app.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@app.errors.count, "error") %>.
    </div>
    <ul>
    <% @app.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
	<p>
		This is a web application created for the sole purpose of facilitating the application submission process to Medtronic's internal app store. This web application aims to replicate the process that involved the repeated exchange of clunky Word  documents.
	</p>
		

app/views/static_pages/help.html.erb
<h1>Help</h1>
	<p>
		If you need any help with this application, just contact <a href="mailto:brandon.j.smith@medtronic.com">Brandon Smith</a>. This application is intended to be easy to use, so he needs to do a better job!
	</p>
		

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the App Submission Web Portal!</h1>

  <h2>
    This is the home page for the new App Submission web application! This web app will facilitate the addition of new applications to Medtronic's own internal App Store.
  </h2>

  <%= link_to "Submit an app now!", '/new', class: "btn btn-large btn-primary" %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the Rails Installer Demo!!!</h1>